[package]
name = "mini-sansio-dbus"
version = "5.0.3"
edition = "2024"
license = "MIT"
repository = "https://github.com/iliabylich/mini-sansio-dbus"
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Sans-IO implementation of DBus protocol"

[dev-dependencies]
anyhow = "1"
rustix = { version = "1", features = ["fs", "event", "net", "time"] }
