[package]
name = "mini-sansio-dbus"
version = "2.0.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/iliabylich/mini-sansio-dbus"
authors = ["Ilya Bylich <ibylich@gmail.com>"]
description = "Sans-IO implementation of DBus protocol"

[dependencies]
rustix = { version = "1", features = ["net"] }

[dev-dependencies]
pretty_env_logger = "0.5"
log = "0.4"
anyhow = "1.0"
rustix = { version = "1", features = ["fs", "event"] }
